tuple_list = (20, 20, 10, 15, 30)
tuple_list_2 = (35, 45, 70)
count_of_tuple_elements = tuple_list.count(20)
print(count_of_tuple_elements)
print(len(tuple_list))
print(max(tuple_list))
print(tuple_list.__len__())
print(tuple_list.__add__(tuple_list_2))
print("New Tuple List:", tuple_list, tuple_list_2)